services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ${BACKEND_IMAGE}
    restart: always
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__PostgreSql: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY:-OHS_SUPER_SECURE_JWT_SECRET_2026_ULTRA_STRONG_KEY_123456}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_KEY: ${JWT_KEY:-OHS_SUPER_SECURE_JWT_SECRET_2026_ULTRA_STRONG_KEY_123456}
      Encryption__CurrentKey: ${ENCRYPTION_CURRENT_KEY}
      Encryption__KeyVersion: ${ENCRYPTION_KEY_VERSION}
      Auth__DemoPassword: ${AUTH_DEMO_PASSWORD}
      Frontend__AllowedOrigin: ${FRONTEND_ORIGIN}
    ports:
      - "8080:8080"

  frontend:
    image: ${FRONTEND_IMAGE}
    restart: always
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
    ports:
      - "3000:3000"

volumes:
  postgres_data:
