services:
  db:
    image: postgres:16-alpine
    container_name: ohs-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/ohs_schema.sql:/docker-entrypoint-initdb.d/01-ohs-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend/Ohs.Api
      dockerfile: Dockerfile
    container_name: ohs-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSql: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__Key: ${JWT_KEY:-OHS_SUPER_SECURE_JWT_SECRET_2026_ULTRA_STRONG_KEY_123456}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_KEY: ${JWT_KEY:-OHS_SUPER_SECURE_JWT_SECRET_2026_ULTRA_STRONG_KEY_123456}
      Encryption__CurrentKey: ${ENCRYPTION_CURRENT_KEY}
      Encryption__KeyVersion: ${ENCRYPTION_KEY_VERSION}
      Auth__DemoPassword: ${AUTH_DEMO_PASSWORD}
      Frontend__AllowedOrigin: ${FRONTEND_ORIGIN}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ohs-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
    ports:
      - "3000:3000"

volumes:
  postgres_data:
