// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Ohs.Api.Data;

#nullable disable

namespace Ohs.Api.Migrations
{
    [DbContext(typeof(OhsDbContext))]
    [Migration("20260502212302_AddIncidentAndAnalysis")]
    partial class AddIncidentAndAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ohs.Api.Domain.AccessLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_access_logs");

                    b.ToTable("access_logs", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.CorrectiveAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset?>("OhsApprovalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ohs_approval_at");

                    b.Property<Guid?>("OhsApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("ohs_approved_by");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_id");

                    b.Property<int>("Status")
                        .HasColumnType("action_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_actions");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("ix_actions_analysis_id");

                    b.HasIndex("ResponsibleId")
                        .HasDatabaseName("ix_actions_responsible_id");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("photo_urls");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<int>("Status")
                        .HasColumnType("incident_status")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("incident_type")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_incidents_location_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_incidents_reporter_id");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.IncidentHealthPayload", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<byte[]>("AuthTag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("auth_tag");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Iv")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("iv");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.HasKey("IncidentId")
                        .HasName("pk_incident_health_payloads");

                    b.ToTable("incident_health_payloads", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.LegalReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid?>("GeneratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<NpgsqlRange<DateOnly>>("Period")
                        .HasColumnType("daterange")
                        .HasColumnName("period");

                    b.Property<int>("Type")
                        .HasColumnType("legal_report_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_legal_reports");

                    b.ToTable("legal_reports", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AreaCode")
                        .HasColumnType("text")
                        .HasColumnName("area_code");

                    b.Property<string>("Building")
                        .HasColumnType("text")
                        .HasColumnName("building");

                    b.Property<string>("Floor")
                        .HasColumnType("text")
                        .HasColumnName("floor");

                    b.Property<string>("LineName")
                        .HasColumnType("text")
                        .HasColumnName("line_name");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("site_name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.HasKey("Id")
                        .HasName("pk_outbox_events");

                    b.ToTable("outbox_events", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.RootCauseAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalystId")
                        .HasColumnType("uuid")
                        .HasColumnName("analyst_id");

                    b.Property<int>("Category")
                        .HasColumnType("analysis_category")
                        .HasColumnName("category");

                    b.Property<string>("Cause1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cause_1");

                    b.Property<string>("Cause2")
                        .HasColumnType("text")
                        .HasColumnName("cause_2");

                    b.Property<string>("Cause3")
                        .HasColumnType("text")
                        .HasColumnName("cause_3");

                    b.Property<string>("Cause4")
                        .HasColumnType("text")
                        .HasColumnName("cause_4");

                    b.Property<string>("Cause5")
                        .HasColumnType("text")
                        .HasColumnName("cause_5");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FishboneJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fishbone_json");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_root_cause_analyses");

                    b.HasIndex("AnalystId")
                        .HasDatabaseName("ix_root_cause_analyses_analyst_id");

                    b.HasIndex("IncidentId")
                        .IsUnique()
                        .HasDatabaseName("ix_root_cause_analyses_incident_id");

                    b.ToTable("root_cause_analyses", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_users_department_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Ohs.Api.Domain.CorrectiveAction", b =>
                {
                    b.HasOne("Ohs.Api.Domain.RootCauseAnalysis", "Analysis")
                        .WithMany("Actions")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_actions_root_cause_analyses_analysis_id");

                    b.HasOne("Ohs.Api.Domain.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_actions_users_responsible_id");

                    b.Navigation("Analysis");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Ohs.Api.Domain.Incident", b =>
                {
                    b.HasOne("Ohs.Api.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .HasConstraintName("fk_incidents_locations_location_id");

                    b.HasOne("Ohs.Api.Domain.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_users_reporter_id");

                    b.Navigation("Location");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Ohs.Api.Domain.IncidentHealthPayload", b =>
                {
                    b.HasOne("Ohs.Api.Domain.Incident", "Incident")
                        .WithOne("HealthPayload")
                        .HasForeignKey("Ohs.Api.Domain.IncidentHealthPayload", "IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_health_payloads_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Ohs.Api.Domain.RootCauseAnalysis", b =>
                {
                    b.HasOne("Ohs.Api.Domain.User", "Analyst")
                        .WithMany()
                        .HasForeignKey("AnalystId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_root_cause_analyses_users_analyst_id");

                    b.HasOne("Ohs.Api.Domain.Incident", "Incident")
                        .WithOne("RootCauseAnalysis")
                        .HasForeignKey("Ohs.Api.Domain.RootCauseAnalysis", "IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_root_cause_analyses_incidents_incident_id");

                    b.Navigation("Analyst");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Ohs.Api.Domain.User", b =>
                {
                    b.HasOne("Ohs.Api.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_users_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Ohs.Api.Domain.Incident", b =>
                {
                    b.Navigation("HealthPayload");

                    b.Navigation("RootCauseAnalysis");
                });

            modelBuilder.Entity("Ohs.Api.Domain.RootCauseAnalysis", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
